# To troubleshoot and get more log info enable ldap debug logging in grafana.ini
# [log]
# filters = ldap:debug

[[servers]]
host = "10.80.0.5"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = false
bind_dn = "cn=ldapadm,dc=ldap,dc=kernelboot,dc=local"
bind_password = 'Orion123'
search_filter = "(uid=%s)"
search_base_dns = ["ou=Peoples,dc=ldap,dc=kernelboot,dc=local"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "uid"
member_of = "memberOf"

[[servers.group_mappings]]
group_dn = "cn=grafana-admin,ou=Peoples,dc=ldap,dc=kernelboot,dc=local"
org_role = "Admin"

[[servers.group_mappings]]
group_dn = "cn=crft,ou=Peoples,dc=ldap,dc=kernelboot,dc=local"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"